auto: true

markdown: rdiscount
pygments: true
google_analytics: true
paginate: 8
permalink: /:title

title: dhong.co
url: http://dhong.co
feed: /atom.xml
author_info: <a href="http://dhong.co/">Duan Hong</a>
